### ISSUE TITLE
When any technology finishes, all roboports get emptied of robots

### ISSUE THREAD

**Issue by LukevanTricht** [HEROgold/bot-batteries-technologies_1.0.0#2] opened 2024-02-24 05:36 UTC
When any of the three technologies get finished researching, all roboports get replaced with new ones, but that replacement doesn't keep the 'bots inside. Went from ~1k bots to 20 when the technology finished.

I suspect something like this would work, inserted in here similar to how `old_energy` is done. Haven't tested it, but will do so when I get the chance -> https://github.com/HEROgold/bot-batteries-technologies_1.0.0/blob/master/control.lua#L75-L89
```
local old_robot_inventory = roboport.get_inventory(defines.inventory.roboport_robot)
local old_materials_inventory = roboport.get_inventory(defines.inventory.roboport_material)
<skip a few>
for i=1,#old_robot_inventory do
    created_rport.get_inventory(defines.inventory.roboport_robot)[i].set_stack(old_robot_inventory[i])
end

for i=1,#old_materials_inventory do
    created_rport.get_inventory(defines.inventory.roboport_material)[i].set_stack(old_materials_inventory[i])
end
```

**Comment by HEROgold** [comment] 2024-02-25 18:41
Hey thanks for the report! 
After a rough weekend I've managed to fix the issue! it seems like the fast_replace_group does work as I thought it should (like replacing inserters or furnaces).
However the game doesn't put roboports in a group by default, i've added a fix for that and now roboports upgrade as intended, and no robots gets lost anymore!

This issue is resolved in version 1.0.5, the factory must grow!

**Closed as completed by HEROgold** 2024-02-25 18:41 UTC
